Extend get drive tests coverage
owncloud/ocis-php-sdk pull request #102
Opened 2023-11-30 12:43 UTC by amrita-shrestha

Add test coverage for getting drive info

2023-12-05 04:13 UTC, S-Panta commented
LGTM

2023-12-05 04:27 UTC, individual-it requested changes
also add a test for:
- order direction

2023-12-05 04:27 UTC, individual-it commented on tests/integration/Owncloud/OcisPhpSdk/OcisTest.php
> +        $this->assertIsObject($drive->getType());
better to test that it has the correct values, not only checking the type

2023-12-05 04:27 UTC, individual-it commented on tests/integration/Owncloud/OcisPhpSdk/OcisTest.php
> +    public function testGetMyDrive(): void
```suggestion
    public function testGetMyDrives(): void
```

2023-12-05 04:27 UTC, individual-it commented on tests/integration/Owncloud/OcisPhpSdk/OcisTest.php
> +        $myDrive = $ocis->getMyDrives();
here it would be good to have other drives and make sure only the drives where a specific user has access are listed

2023-12-05 04:27 UTC, individual-it commented on tests/integration/Owncloud/OcisPhpSdk/OcisTest.php
> +            DriveType::PROJECT
also test for other types, that should be easy with a `dataProvider`

2023-12-05 04:27 UTC, individual-it commented on tests/integration/Owncloud/OcisPhpSdk/OcisTest.php
> +        $this->assertTrue([$managementDrive->getName(),$sportDrive->getName()] === [$drives[1]->getName(),$drives[3]->getName()]);
maybe easier to read if we would use `logicalOr` as done in
https://github.com/owncloud/ocis-php-sdk/blob/d5c6abfe6c1fb0ac2b078d237e7032d30f403ca1/tests/integration/Owncloud/OcisPhpSdk/OcisResourceTest.php#L58-L64

same for other places.

2023-12-05 04:27 UTC, individual-it commented on tests/integration/Owncloud/OcisPhpSdk/OcisTest.php
> +    public function testGetMyDriveInvalidTypeFilter(): void
I don't understand what this test tries to test

2023-12-05 04:27 UTC, individual-it commented on tests/integration/Owncloud/OcisPhpSdk/OcisTest.php
> +        //  $this->assertEquals($sportDrive, $drive);
What about putting the issue link into the `markTestIncomplete` output?

2023-12-13 11:25 UTC, individual-it approved these changes

2023-12-13 11:25 UTC, merged