error message in assertion for GroupTest updated
owncloud/ocis-php-sdk pull request #176
Opened 2024-01-09 10:05 UTC by S-Panta

Related issue:https://github.com/owncloud/ocis-php-sdk/issues/131

2024-01-10 06:53 UTC, amrita-shrestha reviewed
address this review

2024-01-10 06:53 UTC, amrita-shrestha commented on tests/integration/Owncloud/OcisPhpSdk/GroupsTest.php
> +            "Group name should be physicslovers but found "
```suggestion
            "Group should be deleted but exists "
```

2024-01-10 06:53 UTC, amrita-shrestha commented on tests/integration/Owncloud/OcisPhpSdk/GroupsTest.php
> +            "Expected one number of group but got ". count($groups)
```suggestion
            "Expected one group but found ". count($groups)
```

2024-01-10 08:22 UTC, amrita-shrestha approved these changes
lgtm

2024-01-10 11:12 UTC, individual-it requested changes

2024-01-10 11:12 UTC, individual-it commented on tests/integration/Owncloud/OcisPhpSdk/GroupsTest.php
> +                $userName . " user should exist in ". $group->getDisplayName() . " group but found "
```suggestion
                $userName . " user be the first membe in ". $group->getDisplayName() . " group but found "
```

2024-01-11 05:14 UTC, individual-it approved these changes

2024-01-11 05:14 UTC, merged