error message in assertion updated for resource share test
owncloud/ocis-php-sdk pull request #186
Opened 2024-01-15 12:23 UTC by S-Panta

Related issue : https://github.com/owncloud/ocis-php-sdk/issues/131

2024-01-17 04:27 UTC, individual-it requested changes

2024-01-17 04:27 UTC, individual-it commented on tests/integration/Owncloud/OcisPhpSdk/ResourceInviteTest.php
> +        );
what about simplifying it like that

```suggestion
        $this->assertInstanceOf(
            \DateTimeImmutable::class,
            $shareResourceExpirationDateTime,
            "Expected class to be 'DateTimeImmutable'"
            . " but found " . print_r($shareResourceExpirationDateTime, true)
        );
```

2024-01-18 06:49 UTC, individual-it commented on tests/integration/Owncloud/OcisPhpSdk/ResourceInviteTest.php
> +        );
there are more cases like that, e.g. https://github.com/owncloud/ocis-php-sdk/pull/186/files#diff-63ac34bf34e0074dd6979a9dd8623738a73f3d9f457baee479282eb29c1353acR156-R161

2024-01-23 08:57 UTC, amrita-shrestha commented on tests/integration/Owncloud/OcisPhpSdk/ResourceInviteTest.php
> +            "Expected shared resource to be 'to-share-test.txt but found " . $receivedShare->getName()
```suggestion
            "Expected shared resource to be 'to-share-test.txt' but found " . $receivedShare->getName()
```

2024-01-24 07:11 UTC, amrita-shrestha approved these changes
lgtm

2024-01-25 04:25 UTC, amrita-shrestha commented on tests/integration/Owncloud/OcisPhpSdk/ResourceInviteTest.php
> +            "Expected expiration datetime of shared resource doesn't match"
@nirajacharya2 @S-Panta

2024-01-26 03:49 UTC, S-Panta commented on tests/integration/Owncloud/OcisPhpSdk/ResourceInviteTest.php
> +            "Expected expiration datetime of shared resource doesn't match"
Expiration has both a date and time into it. SO, it's better not to change that imo.

2024-01-26 10:38 UTC, merged