error message in assertion updated for OcisTest
owncloud/ocis-php-sdk pull request #189
Opened 2024-01-17 08:46 UTC by S-Panta

Related issue: https://github.com/owncloud/ocis-php-sdk/issues/131

2024-01-18 06:46 UTC, individual-it requested changes

2024-01-18 06:46 UTC, individual-it commented on tests/integration/Owncloud/OcisPhpSdk/OcisTest.php
> +        );
```suggestion
        $this->assertTrue(
            (is_array($drives) && count($drives) > 1),
            " drives variable is expected to be an array but found to be " . gettype($drives) .
            " and to have more than one element but found " . count($drives)
        );
```

2024-01-18 06:46 UTC, individual-it commented on tests/integration/Owncloud/OcisPhpSdk/OcisTest.php
> +            "Expect drivename to be " . $drive->getName() .  " but found " .$sportDrive->getName()
```suggestion
            "Expected drivename to be " . $drive->getName() .  " but found " .$sportDrive->getName()
```

2024-01-18 06:46 UTC, individual-it commented on tests/integration/Owncloud/OcisPhpSdk/OcisTest.php
> +            "Expected group count to be " . count($resultGroups) . "but found " . count($groups)
```suggestion
            "Expected group count to be " . count($resultGroups) . " but found " . count($groups)
```

2024-01-26 05:58 UTC, amrita-shrestha approved these changes
Lgtm

2024-01-26 06:00 UTC, merged