[do-not-merge]bump latest ocis commit id
owncloud/ocis-php-sdk pull request #203
Opened 2024-01-30 06:34 UTC by amrita-shrestha

Currently while adding nightly test runs in drone ci its fails in test scenario so we will work on this PR

2024-01-31 11:43 UTC, amrita-shrestha commented
blocked by https://github.com/owncloud/ocis/issues/8331

2024-02-08 11:26 UTC, amrita-shrestha commented
> blocked by [owncloud/ocis#8331](https://github.com/owncloud/ocis/issues/8331)

add workaround for this issue using constant role id 

checked with moodle-repository-ocis ✅

2024-02-08 11:31 UTC, individual-it requested changes

2024-02-08 11:31 UTC, individual-it commented on src/ShareReceived.php
> +                "Invalid shared modified DateTime'" . print_r($time, true) . "'"
```suggestion
                "Invalid last modified DateTime'" . print_r($time, true) . "'"
```

2024-02-08 11:31 UTC, individual-it commented on src/ShareReceived.php
> +    public function getCreatedByUserName(): string
```suggestion
    public function getCreatedByDisplayName(): string
```

2024-02-08 11:31 UTC, individual-it commented on src/ShareReceived.php
> +    public function getRemoteItemPermission()
this function seems only be used in tests, do we really need it?

2024-02-14 05:03 UTC, amrita-shrestha commented
currently waiting for 

changes on accept/decline share 
- ocis/pull/7885

2024-02-26 05:48 UTC, individual-it approved these changes

2024-02-26 08:25 UTC, merged