Refactor root support implementation
owncloud/ocis-php-sdk pull request #232
Opened 2024-07-12 07:58 UTC by amrita-shrestha

2024-07-14 13:14 UTC, individual-it reviewed
generally looks fine, but is it possible to put the revert of #227 into a separate PR? That would make it easier to review

2024-07-15 04:16 UTC, amrita-shrestha commented
> generally looks fine, but is it possible to put the revert of #227 into a separate PR? That would make it easier to review



> generally looks fine, but is it possible to put the revert of #227 into a separate PR? That would make it easier to review

I don't see any point on doing that. 95% changes falls under recert PR and only 5% changes goes on new PR.

2024-07-15 07:29 UTC, individual-it requested changes

2024-07-15 07:29 UTC, individual-it commented on src/Drive.php
> +     * todo after delete drive object contain old permissions
is this todo done?

2024-07-15 07:29 UTC, individual-it commented on src/Drive.php
> +    public function getPermissionId(string $userId): ?string
1. why limiting this to a specific user? I would like to query all users that have access to the drive. This way I would have to know first a userId and could ask if the user has access. But how to know what userId to ask about?
2. after getting the permissionId I cannot see a way to find out what that permission is allowed to do.
3. according to the example in https://owncloud.dev/libre-graph-api/#/drives.root/ListPermissionsSpaceRoot one user can have multiple permissions

What about having a function called `getPermissions` that returns an array of `DrivePermission`. The `DrivePermission` class can return things like userId and displayname and also the role etc. ?
The setters could be moved ether into that Class or stay inside the `Drive` class and take a complete object as parameter and not only the permission id

2024-07-16 06:01 UTC, phil-davis approved these changes
LGTM - I don't see any problem. This should remove an backward-compatibility issues, and moves forward on inviting and managing for drive roots.

2024-07-16 14:44 UTC, individual-it approved these changes
I've pushed a couple of commits to fix sonarcloud issues.
Please double check if this still works with the moodle extension and if yes, merge the PR

2024-07-16 14:44 UTC, individual-it commented on src/Drive.php
> +            throw new InvalidResponseException(
good idea :+1: 
I thought about returning an empty array in that case, but really an exception is the correct way to do it as a drive should always have some permissions given to some user

2024-07-17 04:05 UTC, merged