sanitizing the URL
owncloud/ocis-php-sdk pull request #25
Opened 2023-10-19 04:09 UTC by S-Panta

Sanitizing the baseurl

2023-10-20 06:40 UTC, amrita-shrestha commented on tests/integration/Owncloud/OcisSdkPhp/OcisTest.php
> +    public function testListDrive(): void
```suggestion
    public function testListMyDrive(): void
```

2023-10-20 06:40 UTC, amrita-shrestha commented on tests/integration/Owncloud/OcisSdkPhp/OcisTest.php
> +    }
```suggestion
    }
    
```

2023-10-20 09:47 UTC, individual-it requested changes

2023-10-20 09:47 UTC, individual-it commented on tests/integration/Owncloud/OcisSdkPhp/OcisTest.php
> +    public function testListMyDriveResponseArrayForMalformedUrl(): void
```suggestion
    public function testServiceUrlTrailingSlash(): void
```

2023-10-20 09:47 UTC, individual-it requested changes

2023-10-20 09:47 UTC, individual-it commented on tests/integration/Owncloud/OcisSdkPhp/OcisTest.php
> +        $ocis = new Ocis('https://ocis.owncloud.test///', $token, ['verify' => false]);
```suggestion
        $ocis = new Ocis($this->ocisUrl . '///', $token, ['verify' => false]);
```

2023-10-30 03:16 UTC, phil-davis commented on tests/output/clover.xml
This should not be committed.

2023-10-30 04:01 UTC, individual-it approved these changes

2023-10-30 04:01 UTC, merged