adding documentation for using education endpoint
owncloud/ocis-php-sdk pull request #265
Opened 2024-09-23 10:48 UTC by nirajacharya2

This PR adds documentation for using education endpoint

related issue: https://github.com/owncloud/ocis-php-sdk/issues/260

2024-09-23 12:24 UTC, phil-davis commented on README.md
> +// for using eduaction endpoint use education api token
```suggestion
// for using education endpoint use education api token
```

2024-09-24 03:51 UTC, individual-it requested changes

2024-09-24 03:51 UTC, individual-it commented on README.md
>  ```
I think this is a bit confusing.
On top we are talking about an `access token`
In between there is an `education api token` but the variable is called `$educationAccessToken`
And then afterwards we tell people how to get an access token.

I think you will have to elaborate about
1. that there are two different tokens for different API endpoints
2. that at least one needs to be provided
3. where to get an education access token
4. which token is needed for which functions
5. which token the chapter below is talking about

2024-09-26 07:46 UTC, individual-it requested changes

2024-09-26 07:46 UTC, individual-it commented on README.md
> +Ocis has two type of access token, One which is used to interact with drive, group, user, shares etc.(OICD access token) and another which can be used to interact with education endpoints (education
```suggestion
Ocis has two types of access tokens, one which is used to interact with drive, group, user, shares etc.(OICD access token) and another one which can be used to interact with education endpoints (education access token).
```

2024-09-26 07:46 UTC, individual-it commented on README.md
> +Or create an Ocis object to interact with education endpoint using the service Url and an education access token:
```suggestion
Or create an Ocis object to interact with education endpoints using the service Url and an education access token:
```

2024-09-26 07:46 UTC, individual-it commented on README.md
> +Atleast one access token should be provided to use the sdk.
```suggestion
At least one access token should be provided to use the SDK.
```

2024-09-27 04:20 UTC, individual-it approved these changes

2024-09-27 06:05 UTC, merged