Document the required php library
owncloud/ocis-php-sdk pull request #34
Opened 2023-10-20 04:10 UTC by amrita-shrestha

This PR adds documentation regarding php library required to run tests

2023-11-20 08:56 UTC, phil-davis commented
@amrita-shrestha please rebase this so it "sees" the current master license.

2023-11-21 11:45 UTC, phil-davis commented
I rebased just now,

2023-12-22 06:35 UTC, individual-it commented
@amrita-shrestha are you still working on this PR?

2024-01-11 09:53 UTC, individual-it requested changes

2024-01-11 09:53 UTC, individual-it commented on tests/README.md
> +`vendor/phpunit/phpunit/phpunit --configuration ./phpunit.xml --testsuite integration --filter testGetResources`
we should put that in the make command

2024-04-23 07:25 UTC, individual-it requested changes

2024-04-23 07:25 UTC, individual-it commented on Makefile
> +	$(PHPUNIT) --configuration ./phpunit.xml --testsuite integration --filter $(filter-out $@,$(MAKECMDGOALS))
can we put that into the normal `test-php-integration` goal?
check if there are any extra arguments, and if yes add `--filter` and if not omit it

2024-04-23 10:23 UTC, merged