implementing adding user to group
owncloud/ocis-php-sdk pull request #58
Opened 2023-11-03 03:19 UTC by nirajacharya2

implementing adding user to group

2023-11-20 08:57 UTC, phil-davis commented
@nirajacharya2  please rebase this so it "sees" the current master license.

2023-11-21 05:46 UTC, amrita-shrestha commented on src/Group.php
> +    /**
```suggestion

    /**
```

2023-11-21 08:29 UTC, individual-it requested changes
w

2023-11-21 08:29 UTC, individual-it commented on src/Group.php
> +    ) {
I think these parameters are not optional (except of `connectionConfig`)
```suggestion
    public function __construct(
        OpenApiGroup $openApiGroup,
        string $serviceUrl,
        array $connectionConfig,
        string &$accessToken
    ) {
```

2023-11-21 08:29 UTC, individual-it commented on src/Group.php
> +    public function addUserToGroup($user)
If possible add the types into the function declaration
```suggestion
    public function addUserToGroup(User $user): void
```

2023-11-21 08:29 UTC, individual-it commented on tests/integration/Owncloud/OcisPhpSdk/OcisTest.php
> +    public function testAddUserAndGroupsExpand(): void
what do you want to test here? adding user or getting group and expanding the members?
If you want to test both, write two separate tests

2023-11-21 08:29 UTC, individual-it commented on src/Group.php
> +    public function addUserToGroup($user)
we know its about adding a user to a group, because we are using the Group class
```suggestion
    public function addUser($user)
```

2023-11-21 08:29 UTC, individual-it commented on src/Group.php
> +        $apiInstance->addMember($this->getId(), $memberRef);
catch the ApiException as we do in other places

2023-11-22 03:15 UTC, individual-it approved these changes

2023-11-22 03:15 UTC, merged